# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  host: localhost
  database: dev
  username: dev
  password: dev
  port: 5437
  <<: *default

test:
  host: localhost
  database: test
  username: dev
  password: dev
  port: 5437
  <<: *default

production:
  <<: *default
  database: candle_store_production
  username: candle_store
  password: <%= ENV['CANDLE_STORE_DATABASE_PASSWORD'] %>
